---
title: "P3-CP2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, error=FALSE, warning=FALSE} 
library(dplyr)
library(ggfortify)
library(cluster)
library(ggdendro)
library(broom)
```


```{r, echo=FALSE, message=FALSE, error=FALSE, warning=FALSE} 
filmes <- read.csv("../dados/meta_data7.csv")
  
filme_personagem <- read.csv("../dados/character_mapping.csv")
  
personagens <- read.csv("../dados/character_list5.csv")

tabela_completa <- left_join(filmes, personagens, "script_id")
```

```{r}
filme_agrupado <- tabela_completa %>% 
  filter(age != 'NULL', !is.na(age), !is.na(year), !is.na(words), !is.na(gross)) %>%
  mutate(age = as.integer(age)) %>% 
  group_by(title) %>%  
  summarise(media_idade = mean(age, na.rm = TRUE), ano_lancamento = first(year), 
            media_palavras = mean(words), media_renda = mean(gross))
```

```{r}
km = filme_agrupado %>% 
  select(-title) %>% 
  kmeans(centers = 4, nstart = 20)


```

