---
title: "P5-CP1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE, message=FALSE, error=FALSE, warning=FALSE} 
library(tidyverse)
library(GGally)
library(ggfortify)
library(broom)
require(ISLR)
library(modelr)

dados <- read.csv("../dados/speed-dating.csv")
dados_mulheres <- dados %>% 
    filter(gender == 0, attr != "NA", sinc != "NA", intel != "NA", fun != "NA", amb != "NA", shar != "NA", like != "NA", prob != "NA")
dados_homens <- dados %>% 
    filter(gender == 1, attr != "NA", sinc != "NA", intel != "NA", fun != "NA", amb != "NA", shar != "NA", like != "NA", prob != "NA")
```

```{r}
ggplot(dados, aes(x = attr, y = like)) + 
  geom_point(alpha = 0.4)
```




```{r}
ggplot(dados_mulheres, aes(x = attr, y = like)) + 
  geom_point(alpha = 0.4)

```

```{r}
dados_homens %>% 
  select(attr, fun, amb, like) %>% 
  ggpairs(lower = list(continuous = wrap("points", alpha = 0.3)))
```



```{r}
dados_mulheres %>% 
  select(attr, fun, shar, like) %>% 
  ggpairs(lower = list(continuous = wrap("points", alpha = 0.3)))

```


```{r}
dados_mulheres = dados_mulheres %>% 
  filter(fun != 0.0, attr != 0.0) %>% 
  mutate(funLog = log2(fun), attrLog = log2(attr))

dados_mulheres.model = lm(like ~ funLog, data = dados_mulheres)

dados_m_augmented = dados_mulheres %>% 
  add_predictions(dados_mulheres.model) %>% 
  add_residuals(dados_mulheres.model)

# Modelo x dados
dados_m_augmented %>% 
  ggplot(aes(x = funLog)) + 
  geom_line(aes(y = pred), size = 2, colour = "blue") + 
  geom_point(aes(y = like))

```

```{r}
dados_mulheres.modelAttr = lm(like ~ attrLog, data = dados_mulheres)

dados_m_augmented_attr = dados_mulheres %>% 
  add_predictions(dados_mulheres.modelAttr) %>% 
  add_residuals(dados_mulheres.modelAttr)

# Modelo x dados
dados_m_augmented_attr %>% 
  ggplot(aes(x = attrLog)) + 
  geom_line(aes(y = pred), size = 2, colour = "blue") + 
  geom_count(aes(y = like))

```

```{r}
tidy(dados_mulheres.model, conf.int = TRUE)
tidy(dados_mulheres.modelAttr, conf.int = TRUE)
```


2. Quais variaveis qualificadas por um candidato explicam melhor a nota atribuida a ele?

```{r}
dados_mulheres_multi = lm(like ~ fun + attr + shar, data = subset(dados_mulheres, select = -c(field,from,career)))
adv_augmented = dados_mulheres %>% 
  add_predictions(dados_mulheres_multi) %>% 
  add_residuals(dados_mulheres_multi)

adv_augmented %>% 
  ggplot(aes(x = like)) + 
  geom_count(aes(y = resid))

glance(dados_mulheres_multi, conf.int = TRUE)
tidy(dados_mulheres_multi, conf.int = TRUE)
autoplot(dados_mulheres_multi)
```



